server:
  port: 9000
spring:
  application:
    name: spring-lb-invoker
spring-lb-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.jack.cloud.MyRule
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka