server:
  port: 9101

spring:
  datasource:
    url: jdbc:mysql://192.168.1.113:3306/jack-test
    username: root
    password: nihaoma
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  application:
    name: storage-mysql

