zookeeper:
  enable: true
  server: 192.168.4.203:3179,192.168.4.203:3180,192.168.4.203:3181
  namespace: demo
  # zkCli.sh acl命令 addauth digest mpush
  #digest: rt:rt
  # 会话超时时间，单位为毫秒，默认60000ms，连接断开后，其它客户端还能申请到临时节点的时间
  sessionTimeoutMs: 60000
  # 连接创建超时时间，单位为毫秒
  connectionTimeoutMs: 6000
  # 最大重试次数
  maxRetries: 3
  # 初始sleep时间，单位毫秒
  baseSleepTimeMs: 1000