server:
  port: 9020

spring:
  redis:
    database: 8
    host: 192.168.4.202
    port: 6379
    jedis:
      pool:
        min-idle: 30
        max-idle: 60
        max-wait: 60000ms
        max-active: 200
    timeout: 5000ms
    password: V5yrNjwd9U53Vfg3U37wEdKca3
  application:
    name: cache-redis