eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:eureka-server-cluster} # 服务主机名
    appname: ${spring.application.name} # 服务名称，默认为 unknow 这里直接取 spring.application.name
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 定义实例ID格式
  client:
    register-with-eureka: false # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己，默认为true
    fetch-registry: false # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false，默认为true
  server:
    enable-self-preservation: false # 关闭自我保护模式
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL:5000}  # 清除节点
    use-read-only-response-cache: ${EUREKA_BOOL_CACHE:false}  # 此处不开启缓存

spring:
  security:
    user:
      name: luozy
      password: jack123
  application:
    name: eureka-server-cluster # 注册中心的名称
  profiles:
    active: master # 默认启动master