spring:
  application:
    name: ek-provider
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: jack-hightech-company
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.netflix: debug
    