server:
  port: 8080
spring:
  application:
    name: spring-boot-rabbitmq-provider
  # 配置RabbitMQ服务器
  rabbitmq:
    host: 192.168.4.203
    port: 5672
    username: admin
    password: admin@123
    # 虚拟host 可以不设置，使用server默认host
    virtual-host: jack-host
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
