server:
  port: 8081
spring:
  application:
    name: ek-invoker
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.netflix: debug